# Generated by Django 3.2.25 on 2025-08-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_doc', models.FileField(blank=True, null=True, upload_to='media/contract/')),
                ('completion', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('end_date', models.DateField()),
                ('signed_date', models.DateField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('for_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtype')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
