# Generated by Django 3.2.25 on 2025-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_doc',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
